/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab4.frame;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class bai1 extends javax.swing.JFrame {

    /**
     * Creates new form bai1
     */
    public bai1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jMenuItem2 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNewItem = new javax.swing.JMenuItem();
        menuOpenItem = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRedItem = new javax.swing.JMenuItem();
        menuGreenItem = new javax.swing.JMenuItem();
        menuBlueItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuTextColorchkItem = new javax.swing.JCheckBoxMenuItem();
        menuExitItem = new javax.swing.JMenu();
        menuAboutUsItem = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new-icon-16.png"))); // NOI18N
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);
        jToolBar1.add(jSeparator1);

        jButton2.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/icon/Apps-preferences-desktop-user-password-icon-16.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator3);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        txtText.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtText.setText("Ngo Tan Cang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtText, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(txtText, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE)));

        jScrollPane2.setViewportView(txtNote);

        jMenu1.setText("File");

        menuNewItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new-icon-16.png"))); // NOI18N
        menuNewItem.setText("New");
        menuNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewItemActionPerformed(evt);
            }
        });
        jMenu1.add(menuNewItem);

        menuOpenItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open-file-icon-16.png"))); // NOI18N
        menuOpenItem.setText("Open");
        menuOpenItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenItemActionPerformed(evt);
            }
        });
        jMenu1.add(menuOpenItem);

        menuSave.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/icon/Custom-Icon-Design-Pretty-Office-7-Save.16.png"))); // NOI18N
        menuSave.setText("Save");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menuSave);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Color");

        menuRedItem.setText("Red");
        buttonGroup1.add(menuRedItem);
        menuRedItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRedItemActionPerformed(evt);
            }
        });
        jMenu2.add(menuRedItem);

        menuGreenItem.setText("Green");
        buttonGroup1.add(menuGreenItem);
        menuGreenItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGreenItemActionPerformed(evt);
            }
        });
        jMenu2.add(menuGreenItem);

        menuBlueItem.setText("Blue");
        buttonGroup1.add(menuBlueItem);
        menuBlueItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBlueItemActionPerformed(evt);
            }
        });
        jMenu2.add(menuBlueItem);
        jMenu2.add(jSeparator4);

        menuTextColorchkItem.setSelected(true);
        menuTextColorchkItem.setText("Text Color");
        jMenu2.add(menuTextColorchkItem);

        jMenuBar1.add(jMenu2);

        menuExitItem.setText("System");

        menuAboutUsItem.setText("About us");
        menuAboutUsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutUsItemActionPerformed(evt);
            }
        });
        menuExitItem.add(menuAboutUsItem);

        jMenuItem9.setText("Exit");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuExitItem.add(jMenuItem9);

        jMenuBar1.add(menuExitItem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        pack();
    }// </editor-fold>

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        txtNote.setText("");
    }

    private void menuOpenItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFileChooser jfile = new JFileChooser();
        int result = jfile.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                txtNote.setPage("file:///" + jfile.getSelectedFile().getPath());
            } catch (IOException ex) {
                Logger.getLogger(bai1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void menuNewItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        txtNote.setText("");
    }

    private void menuRedItemActionPerformed(java.awt.event.ActionEvent evt) {
        // menuRedItem
        if (menuTextColorchkItem.isSelected()) {
            txtText.setForeground(Color.red);
        } else {
            txtText.setBackground(Color.red);
        }

    }

    private void menuGreenItemActionPerformed(java.awt.event.ActionEvent evt) {
        //
        if (menuTextColorchkItem.isSelected()) {
            txtText.setForeground(Color.GREEN);
        } else {
            txtText.setBackground(Color.GREEN);
        }

    }

    private void menuBlueItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (menuTextColorchkItem.isSelected()) {
            txtText.setForeground(Color.BLUE);
        } else {
            txtText.setBackground(Color.BLUE);
        }

    }

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);

    }

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFileChooser jfcs = new JFileChooser();
        int result = jfcs.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fname = jfcs.getSelectedFile();
            try {
                PrintWriter pw = new PrintWriter(fname);
                pw.print(txtNote.getText());
                pw.close();

            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Lab 4 bai 1\nAuthor: CangNgo\nLast update: 17/02/2024\nEducation: FPT");
    }

    private void menuAboutUsItemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Lab 4 bai 1\nAuthor: CangNgo\nLast update: 17/02/2024\nEducation: FPT");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnNew;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuAboutUsItem;
    private javax.swing.JMenuItem menuBlueItem;
    private javax.swing.JMenu menuExitItem;
    private javax.swing.JMenuItem menuGreenItem;
    private javax.swing.JMenuItem menuNewItem;
    private javax.swing.JMenuItem menuOpenItem;
    private javax.swing.JMenuItem menuRedItem;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JCheckBoxMenuItem menuTextColorchkItem;
    private javax.swing.JTextPane txtNote;
    private javax.swing.JTextField txtText;
    // End of variables declaration
}
